### ISSUE TITLE
Dated Documentation on the Website

### ISSUE THREAD

**Issue by stef-rausch** [curvedmark/roole#65]
Just have downloaded Roole 0.2.3 and had a look a the website documentation-wise. It looks like - according to the discussions happening here - that the docs are referring to the 0.2.1 version. You might update the download link ( or at least the button text ) too :wink:

**Comment by curvedmark** [comment]
Sometimes the version of the published npm module is different from that in the documentation, it's because I made some changes to the CLI or something specific to the npm module which doesn't affect the core of Roole. So if I were to release 0.2.3 on the website, the downloaded file would have been exactly the same as 0.2.1, except for the version number in the comment.

But I agree it's misleading, and should come up a way to resolve this. Maybe state it in the website, or state it in the CLI help message, or even delay publishing the npm module until the core is changed.

All doesn't sound very optimal. Ideas are welcomed.

**Comment by stef-rausch** [comment]
Ok. What about keeping the website updated according to the npm module? Even if the changes are "under the hood" only - which is totally fine - it would give re-assurance that one has the most current version running / that the documentation is not lacking behind.

I would not delay the publishing of the npm module. Just my 0.02.

**Comment by curvedmark** [comment]
I will take the advice and release a new version in the website even if the changes are node specific. Since the CLI is somewhat stable now, this should happen pretty rarely.

Thanks.
