### ISSUE TITLE
Lists - How to get started?

### ISSUE THREAD

**Issue by zspecza** [curvedmark/roole#97]
Hey, loving the project's concepts and playing around a little. Tried making a few mixins and functions but ran into a hurdle:

Is it possible to create a blank list/variable? Something like this:

```
$list = ()
OR
$list = []
```

Secondly, is there a way to append a value to a list? I've tried this:

```
$keys = @function $b {
  @for $i in 1..9 {
    $b += $i
  }
  @return $b;
};
```

But that gives me an error - cannot assign number to null.

I've read the whole project home page and can't see much mention of basic features like that - if they are present, could you add them to the docs? :smile:

**Comment by curvedmark** [comment]
These aren't possible yet. Will be implement in a later version.

Not sure about overloading `+`. Since the current syntax doesn't have a nice way to denote a list with just one item, roole treats lists with one item and single values pretty much the same way. It can get pretty confusing when doing things like `1 + 2` (`1 2` or `3`?)

`[1]` sounds like a reasonable syntax, but then you have to deal with `[1 2]`, `[1, 2]` (which should be exactly the same as `1 2`, `1, 2`. two different syntaxes for the same thing?)

Part of the reason they are still not implemented. :)

**Comment by zspecza** [comment]
Perhaps you could get by with just a blank variable delimiter. I still like the `$var = []` syntax for such a thing, or perhaps `$var = ()`, and then add an `append()` function for adding values. And `$var[1]` to fetch a specific part of the list... I would really like to try submitting this as a PR, but compilers/parsers/lexers/grammars are a little over my head at the moment - I wouldn't know where to start!

**Comment by curvedmark** [comment]
Just come up with this idea: list containing only one item can be expressed as `(1)`. Generally, for `(expression)`, if it's preceded or followed by an operator, then it's a regular quotation, otherwise it's a list containing `expression`.
- `()` = empty list
- `(1 + 2)` = a list containing `3`
- `(1 + 2) - 1` = `2`
- `1 + (2 - 1)` = `2`
- `+(1 + 2)` = `3`
- `a (b c) d` = a list containing `a`, list (that contains `b` and `c`) and `d`
- `(a b)` = a list containing list (that contains `a` and `b`)
- `(@function { @return 1 })()` = `1`

Just write down my mind without serious contemplation. Some maybe a terrible decision.

**Comment by curvedmark** [comment]
Added square bracket list syntax in master.

So there are two syntaxes for list objects. When there are more than (including) two items in a list, the brackets are optional. `[1, 2 3]` is the same as `1, 2 3`.

`[]` is the empty list, `[1]` is a single-item list.
